anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "9h3kHWEExHGyUyEtDhSgRufYqM3BdG4THKcKCny4jZuc"

[programs.devnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "9h3kHWEExHGyUyEtDhSgRufYqM3BdG4THKcKCny4jZuc"

[programs.testnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "9h3kHWEExHGyUyEtDhSgRufYqM3BdG4THKcKCny4jZuc"

[programs.localnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "9h3kHWEExHGyUyEtDhSgRufYqM3BdG4THKcKCny4jZuc"
