anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

# [provider]
# cluster = "localnet"
# wallet = "./tests/test-key.json"

[provider]
cluster = "devnet"
wallet = "./local/keys/authority_8EAcZrXUaJZoByMHBC3Kh913hizxJAJkjX3NsLx1g9Ft.json"


[programs.mainnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "ALUFRuJCRacDhtKiMNJ43GtQ1q7Q9U8FKDJdp4VMyTwU"

[programs.devnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "ALUFRuJCRacDhtKiMNJ43GtQ1q7Q9U8FKDJdp4VMyTwU"

[programs.testnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "ALUFRuJCRacDhtKiMNJ43GtQ1q7Q9U8FKDJdp4VMyTwU"

[programs.localnet]
cardinal_stake_pool = "CYUGdQhsWCKXTWgbyuybhRfPTshxneywND8KnHeMfwQe"
cardinal_reward_distributor = "ALUFRuJCRacDhtKiMNJ43GtQ1q7Q9U8FKDJdp4VMyTwU"
